development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: face_development
  pool: 5
  username: postgres
  password: welcome1
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: face_tese
  pool: 5
  username: postgres
  password: welcome1
production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: face_production
  pool: 5
  username: postgres
  password: welcome1